title: Macks Projects
logo: Plaidhat_cybersecurity_lolololol.png
description: A centeralized location for documenting and showcasing personal projects.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal

